config/routes.rb
Rails.application.routes.draw do

  root 'quotes#index'

  resources :posts do
    member do
      put "like", to: "posts#upvote"
    end
  end

  resources :creators

  resources :sources

  resources :themes

  resources :boards

  resources :users

  resources :quotes do
    member do
      put "like", to: "quotes#upvote"
    end
  end

  get 'login', to: 'sessions#new'
  resources :sessions, only: [:new, :create, :destroy]

  delete "/logout", to: "sessions#destroy"

end

app/models/board.rb
class Board < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :posts
  has_and_belongs_to_many :themes
end

app/models/creator.rb
class Creator < ActiveRecord::Base
  has_many :quotes
  has_many :sources
end

app/models/post.rb
class Post < ActiveRecord::Base
  acts_as_votable
  belongs_to :user
  belongs_to :quote
  has_and_belongs_to_many :boards
  # has_many :themes, through :quotes

  has_attached_file :image, styles: { medium: "300x300>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/quote.rb
class Quote < ActiveRecord::Base
  acts_as_votable
    has_and_belongs_to_many :users
    belongs_to :creator
    has_and_belongs_to_many :themes
    has_many :posts
    belongs_to :source

    accepts_nested_attributes_for :creator
    accepts_nested_attributes_for :source

    # calendar :through example:
    # has_many :event_users
    # has_many :active_event_users, -> { where active: true }, class_name: 'EventUser'
    # has_many :active_events, :through => :active_event_users, class_name: 'Event', :source => :event
end

app/models/source.rb
class Source < ActiveRecord::Base
  has_many :quotes
  belongs_to :creator
end

app/models/theme.rb
class Theme < ActiveRecord::Base
  has_and_belongs_to_many :quotes
  has_and_belongs_to_many :boards
  has_and_belongs_to_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :email, presence: true, uniqueness: true

  has_and_belongs_to_many :quotes
  has_and_belongs_to_many :themes
  has_many :boards
  has_many :posts

end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show, :edit, :update, :destroy]

  def index
    @boards = Board.all
  end

  def show
  end

  def new
    @board = Board.new
  end

  def edit
  end

  def create
    @board = Board.new board_params
    if @board.save
      redirect_to boards_path, notice: "Successfully created new Person!"
    else
      render 'new'
    end
  end

  def update
    if @board.update board_params
      redirect_to boards_path, notice: "Created updated!"
    else
      render 'edit'
    end
  end

  def destroy
    @board.destroy
    redirect_to boards_path
  end


  private
    def set_board
      @board = Board.find(params[:id])
    end

    def board_params
      params.require(:board).permit(:stylesheet, :user_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :upvote]


  def index
    @posts = Post.all
  end

  def show
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new post_params
    @user = current_user
    @user.posts << @post
    if @post.save
      redirect_to post_path(@post.id), notice: "Successfully created new post!"
    else
      render 'new'
    end
  end

  def update
    if @post.update post_params
      redirect_to post_path(@post.id), notice: "Post updated!"
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  def upvote
    @post.upvote_by current_user
    redirect_to :back
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:background, :stylesheet, :image, :description)
    end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: [:show, :edit, :update, :destroy, :upvote]

  def index
    @quotes = Quote.all.order("created_at DESC")
    @posts = Post.all.order("created_at DESC")
  end

  def new
    @quote = current_user.quotes.build
    # @creator = Creator.new
    # @source = Source.new
  end

  def create
    # defaults = {:content=>"", :creator_attributes[:name]=>"", :source_attributes[:title]=>""}
    # quote_params = defaults.merge(quote_params)
    @quote = current_user.quotes.build(quote_params)
    # @creator = Creator.where(params[:creator_attributes][:name]).first_or_create
    # @source = Source.where(params[:source_attributes][:title]).first_or_create
    @user = current_user
    @user.quotes << @quote
    # @creator.quotes << @quote
    # @source.quotes << @quote
    if @quote.save # && @creator.save && @source.save
      redirect_to @quote, notice: "Successfully created new quote!"
    else
      render 'new'
    end
  end

  def show
  end

  def edit
    # @quote = Quote.new(quote_params)
    # @creator = Creator.new(quote_params[creator_attributes])
    # @source = Source.new(quote_params[source_attributes])
    # @creator = Creator.where(params[:creator_attributes][:name]).first_or_create
    # @source = Source.where(params[:source_attributes][:title]).first_or_create
  end

  def update
    if @quote.update quote_params
      redirect_to @quote, notice: "Quote was successfully updated!"
    else
      render 'edit'
    end
  end

  def destroy
    @quote.destroy
    redirect_to quotes_path, notice: "Quote deleted!"
  end

  def upvote
    @quote.upvote_by current_user
    redirect_to :back
  end

  private
      def set_quote
        @quote = Quote.find(params[:id])
      end

      def quote_params
        params.require(:quote).permit(:content, creator_attributes: [:name], source_attributes: [:title])
      end
end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
  before_action :set_theme, only: [:show, :edit, :update, :destroy]

  def index
    @themes = Theme.all
  end

  def show
  end

  def new
    @theme = Theme.new
  end

  def edit
  end

  def create
    @theme = Theme.new theme_params
    if @theme.save
      redirect_to themes_path, notice: "Successfully created new theme!"
    else
      render 'new'
    end
  end

  def update
    if @theme.update theme_params
      redirect_to themes_path, notice: "Theme updated!"
    else
      render 'edit'
    end
  end

  def destroy
    @theme.destroy
    redirect_to themes_path
  end


  private
    def set_theme
      @theme = Theme.find(params[:id])
    end

    def theme_params
      params.require(:theme).permit(:tag)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
    @user = current_user
    @quotes = @user.quotes.all.order("created_at DESC")
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new user_params
    if @user.save
      redirect_to login_path
    else
      render 'new'
    end
  end

  def update
    if @user.update user_params
      redirect_to user_path(@user.id)
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    redirect_to login_path
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:f_name, :l_name, :username, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/board_helper.rb
module BoardHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/creators_helper.rb
module CreatorsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/sources_helper.rb
module SourcesHelper
end

app/helpers/theme_helper.rb
module ThemeHelper
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/posts/_form.html.haml
= simple_form_for @post, html: {multipart: true} do |f|
  - if @post.errors.any?
    #errors
      %h2
      = pluralize(@post.errors.count, "error")
      prevented this Post from saving
      %ul
        - @post.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.input :image, input_html: {class:'form-control'}

  .form-group
    = f.input :description, input_html: {class:'form-control'}

  = f.button :submit, class: "btn btn-primary"

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= image_tag @post.image.url(:medium) %>
<%= render 'form' %>
<%= link_to "Nevermind", @post, :class => "btn btn-default" %>

app/views/posts/index.html.erb
<h1>Posts</h1>
<div class="transitions-enabled" id="posts">
<% @posts.each do |post| %>
  <div class="box panel panel-default">
    <%= link_to (image_tag post.image.url(:medium)), post %>
    <div class="panel-body">
      <h2><%= link_to post.description, post  %></h2>
    </div>
    <div class="panel-footer">
      <div class="row">
        <div class="col-md-3">
          <div class="likes pull-left">
            <%= link_to like_post_path(post), :class => "btn btn-xs", method: :put do %>
              <span class="glyphicon glyphicon-heart">
                <%= post.get_upvotes.size %>
              </span>
            <% end %>
          </div>
        </div>
        <div class="col-md-9">
          <div class="btn-group pull-right">
            <%= link_to "All Posts", posts_path, :class => "btn btn-xs"  %>
            <% if current_user %>
              <%= link_to "Edit", edit_post_path(post), :class => "btn btn-xs" %>
              <%= link_to "Delete", post_path(post), :class => "btn btn-xs", method: :delete, data: {confirm: "Are you sure? Such a shame when inspiration dies..."} %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= render 'form' %>
<%= link_to "Nevermind", posts_path, :class => "btn btn-default" %>

app/views/posts/show.html.erb
<div id="post_show" class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="panel panel-default">
      <div class="panel-heading post-image">
        <%= image_tag @post.image.url(:medium) %>
      </div>
      <div class="panel-body">
        <%= @post.description %>
      </div>
      <div class="panel-footer">
        <div class="row">
          <div class="col-md-3">
            <div class="likes pull-left">
              <%= link_to like_post_path(@post), :class => "btn btn-default", method: :put do %>
                <span class="glyphicon glyphicon-heart">
                  <%= @post.get_upvotes.size %>
                </span>
              <% end %>
            </div>
          </div>
          <div class="col-md-6">
            <div class="btn-group">
              <%= link_to "All Posts", posts_path, :class => "btn btn-default"  %>
              <% if current_user %>
                <%= link_to "Edit", edit_post_path, :class => "btn btn-default" %>
                <%= link_to "Delete", post_path, :class => "btn btn-default", method: :delete, data: {confirm: "Are you sure? Such a shame when inspiration dies..."} %>
              <% end %>
            </div>
          </div>
          <div class="col-md-3">
            <p class="user">
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/quotes/_form.html.erb
<div class="col-md-10 col-md-offset-1">
<%= form_for @quote do |f| %>
  <div class="form-group">
    <h2><%= f.label :quote %></h2>
  </div>
  <div class="form-group">
    <%= f.text_area :content, placeholder: "you don't say..." %>
  </div>
  <div class="form-group">
    <%= f.fields_for :creator, @quote.creator do |c| %>
      <%= c.label :creator %>
      <%= c.text_field :creator %>
    <% end %>
  </div>
  <div class="form-group">
    <%= f.fields_for :source, @quote.source do |s| %>
      <%= s.label :source %>
      <%= s.text_field :source %>
    <% end %>
  </div>
  <div class="form-group">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/quotes/_form.html.haml
-# = simple_form_for @pin, html: {multipart: true} do |f|
-#   - if @pin.errors.any?
-#     #errors
-#       %h2
-#       = pluralize(@pin.errors.count, "error")
-#       prevented this Pin from saving
-#       %ul
-#         - @pin.errors.full_messages.each do |msg|
-#           %li= msg
-#
-#   .form-group
-#     = f.input :content, input_html: {class:'form-control'}
-#
-#   .form-group
-#     = f.input :creator, input_html: {class:'form-control'}
-#
-#   .form-group
-#     = f.input :source, input_html: {class:'form-control'}
-#
-#   - f.button :submit, class: "btn btn-primary"

app/views/quotes/edit.html.erb
<h1>Edit Quote</h1>

<%= render 'form' %>

<%= link_to "Nevermind", quote_path, :class => "btn btn-default" %>

app/views/quotes/index.html.erb
<h1>Welcome to Quotilia</h1>
<h2>Get Inspired</h2>
<div class="transitions-enabled" id="posts">
<% @posts.each do |post| %>
  <div class="box panel panel-default">
    <%= link_to (image_tag post.image.url(:medium)), post %>
    <div class="panel-body">
      <h2><%= link_to post.description, post  %></h2>
    </div>
    <div class="panel-footer">
      <div class="row">
        <div class="col-md-3">
          <div class="likes pull-left">
            <%= link_to like_post_path(post), :class => "btn btn-xs", method: :put do %>
              <span class="glyphicon glyphicon-heart">
                <%= post.get_upvotes.size %>
              </span>
            <% end %>
          </div>
        </div>
        <div class="col-md-9">
          <div class="btn-group pull-right">
            <% if current_user %>
              <%= link_to "Edit", edit_post_path(post), :class => "btn btn-xs" %>
              <%= link_to "Delete", post_path(post), :class => "btn btn-xs", method: :delete, data: {confirm: "Are you sure? Such a shame when inspiration dies..."} %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>
<% @quotes.each do |n| %>
  <div class="box panel panel-default">
    <div class="quote">
      <div class="content panel-body">
        <h3>"<%= n.content %>"</h3>
      </div>
      <div class="panel-footer">
          <div class="quoters">
            <% n.users.each do |p| %>
              <div class="quoter">
                <%= "Quoted by #{p.f_name} #{p.l_name}" %>
              </div>
            <% end %>
          </div>
          <div class="btn-group">
            <%= link_to "Details", quote_path(n), :class => "btn btn-xs"  %>
            <% if current_user %>
              <%= link_to "Edit", edit_quote_path(n), :class => "btn btn-xs"  %>
              <%= link_to "Delete", quote_path(n), :class => "btn btn-xs", method: :delete, data: {confirm: "Are you sure? Such a shame when knowledge is wasted..."} %>
            <% end %>
          </div>
      </div>
    </div>
  </div>
<% end %>
</div>

app/views/quotes/new.html.erb
<h1>Share Some Wisdom</h1>

<%= render 'form' %>

<%= link_to "Nevermind", quotes_path, :class => "btn btn-default" %>

app/views/quotes/new.html.haml
-# %h1 New Form
-#
-# = render 'form'
-#
-# = link_to "Back", quotes_path

app/views/quotes/show.html.erb
<div class="quote">
  <div class="content">
    <h3>"<%= @quote.content %>"</h3>
  </div>
</div>

<div class="Quoters">
  Quoted by
  <% @quote.users.each do |p| %>
    <%= "#{p.f_name} #{p.l_name}" %>
  <% end %>
</div>

<%= link_to "All Quotes", quotes_path, :class => "btn btn-default"  %>
<%= link_to "Edit", edit_quote_path, :class => "btn btn-default"  %>
<%= link_to "Delete", quote_path, :class => "btn btn-default", method: :delete, data: {confirm: "Are you sure? Such a shame when knowledge is wasted..."} %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
  <div class="error_messages">
    <h2>Form is invalid</h2>
    <ul>
      <% for message in @user.errors.full_messages %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <form class="form-inline col-md-6 col-md-offset-3">
    <div class="form-group">
      <div class="field">
        <%= f.text_field :f_name, :placeholder => 'First Name'  %>
      </div>
      <div class="field">
        <%= f.text_field :l_name, :placeholder => 'Last Name' %>
      </div>
    </div>
    <div class="field">
      <%= f.text_field :username, :placeholder => 'Username' %>
    </div>
    <div class="field">
      <%= f.text_field :email, :placeholder => 'Email' %>
    </div>
    <div class="field">
      <%= f.password_field :password, :placeholder => 'Password'%>
    </div>
    <div class="field">
      <%= f.password_field :password_confirmation, :placeholder => 'Reenter Password' %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/users/edit.html.erb
<h1>Account Settings</h1>

<%= render 'form' %>

app/views/users/new.html.erb
<h1>Welcome to Quotilia!</h1>

<h1>Sign Up</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1><%= "#{@user.f_name}" %>'s Quotes</h1>
<div class="transitions-enabled" id="posts">
<% @current_user.quotes.each do |n| %>
<div class="box panel panel-default">
  <div class="quote">
    <div class="content panel-body">
      <h3>"<%= n.content %>"</h3>
    </div>
    <div class="panel-footer">
    <div class="quoters">
      Quoted by
      <% n.users.each do |p| %>
        <div class="quoter">
          <%= "#{p.f_name} #{p.l_name}" %>
        </div>
      <% end %>
    </div>
    <div class="btn-group">
      <%= link_to "Details", quote_path(n), :class => "btn btn-xs" %>
      <% if current_user %>
        <%= link_to "Edit", edit_quote_path(n), :class => "btn btn-xs" %>
        <%= link_to "Delete", quote_path(n), :class => "btn btn-xs", method: :delete, data: {confirm: "Are you sure? Such a shame when knowledge is wasted..."} %>
      <% end %>
    </div>
  </div>
  </div>
</div>
<% end %>
</div>
<h1><%= "#{@user.f_name}"%>'s Posts</h1>
<div class="transitions-enabled" id="posts">
<% @current_user.posts.each do |post| %>
<div id="post_show" class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="panel panel-default">
      <div class="panel-heading post-image">
        <%= image_tag post.image.url(:medium) %>
      </div>
      <div class="panel-body">
        <%= post.description %>
      </div>
      <div class="panel-footer">
        <div class="row">
          <div class="col-md-3">
            <div class="likes pull-left">
              <%= link_to like_post_path(post), :class => "btn btn-default", method: :put do %>
                <span class="glyphicon glyphicon-heart">
                  <%= post.get_upvotes.size %>
                </span>
              <% end %>
            </div>
          </div>
          <div class="col-md-6">
            <div class="btn-group">
              <%= link_to "All Posts", posts_path, :class => "btn btn-default"  %>
              <% if current_user %>
                <%= link_to "Edit", edit_post_path, :class => "btn btn-default" %>
                <%= link_to "Delete", post_path, :class => "btn btn-default", method: :delete, data: {confirm: "Are you sure? Such a shame when inspiration dies..."} %>
              <% end %>
            </div>
          </div>
          <div class="col-md-3">
            <p class="user">
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>
</div>