config/routes.rb
Rails.application.routes.draw do

  root 'quotes#index'

  resources :posts do
    member do
      put "like", to: "posts#upvote"
    end
  end

  resources :creators

  resources :sources

  resources :themes

  resources :boards

  resources :users

  resources :quotes do
    member do
      put "like", to: "quotes#upvote"
    end
  end

  get 'login', to: 'sessions#new'
  resources :sessions, only: [:new, :create, :destroy]

  delete "/logout", to: "sessions#destroy"

end

app/models/board.rb
class Board < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :posts
  has_and_belongs_to_many :themes
end

app/models/creator.rb
class Creator < ActiveRecord::Base
  has_many :quotes
  has_many :sources
end

app/models/post.rb
class Post < ActiveRecord::Base
  acts_as_votable
  belongs_to :user
  belongs_to :quote
  has_and_belongs_to_many :boards
  # has_many :themes, through :quotes

  has_attached_file :image, styles: { medium: "300x300>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/quote.rb
class Quote < ActiveRecord::Base
  acts_as_votable
    has_and_belongs_to_many :users
    belongs_to :creator
    has_and_belongs_to_many :themes
    has_many :posts
    belongs_to :source

    accepts_nested_attributes_for :creator
    accepts_nested_attributes_for :source

    # calendar :through example:
    # has_many :event_users
    # has_many :active_event_users, -> { where active: true }, class_name: 'EventUser'
    # has_many :active_events, :through => :active_event_users, class_name: 'Event', :source => :event
end

app/models/source.rb
class Source < ActiveRecord::Base
  has_many :quotes
  belongs_to :creator
end

app/models/theme.rb
class Theme < ActiveRecord::Base
  has_and_belongs_to_many :quotes
  has_and_belongs_to_many :boards
  has_and_belongs_to_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :email, presence: true, uniqueness: true

  has_and_belongs_to_many :quotes
  has_and_belongs_to_many :themes
  has_many :boards
  has_many :posts

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :upvote]


  def index
    @posts = Post.all
  end

  def show
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new post_params
    @user = current_user
    @user.posts << @post
    if @post.save
      redirect_to post_path(@post.id), notice: "Successfully created new post!"
    else
      render 'new'
    end
  end

  def update
    if @post.update post_params
      redirect_to post_path(@post.id), notice: "Post updated!"
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  def upvote
    @post.upvote_by current_user
    redirect_to :back
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:background, :stylesheet, :image, :description)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
    @user = current_user
    @quotes = @user.quotes.all.order("created_at DESC")
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new user_params
    if @user.save
      redirect_to login_path
    else
      render 'new'
    end
  end

  def update
    if @user.update user_params
      redirect_to user_path(@user.id)
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    redirect_to login_path
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:f_name, :l_name, :username, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/board_helper.rb
module BoardHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/creators_helper.rb
module CreatorsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/sources_helper.rb
module SourcesHelper
end

app/helpers/theme_helper.rb
module ThemeHelper
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Quotilia</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Quotilia", quotes_path, :class => "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <% if current_user %>
      <!-- <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Find Quotes</button>
      </form> -->
      <div class="navbar-left">
        <%= link_to "Add Quote", new_quote_path, :class => "btn btn-default navbar-btn"  %>
      </div>
      <div class="navbar-left">
        <%= link_to "Create Post", new_post_path, :class => "btn btn-default navbar-btn"  %>
      </div>
      <% end %>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.username %><span class="caret"></span></a>
              <ul class="dropdown-menu">
                  <li> <%= link_to "Dashboard", user_path(current_user.id) %> </li>
                  <li> <%= link_to "Account", edit_user_path(current_user.id) %> </li>
                  <li role="separator" class="divider"></li>
                  <li> <%= link_to "Logout", logout_path, method: :delete, data: {confirm: 'Are you sure?'} %> </li>
              </ul>
          </li>
        <% else %>
            <li><%= link_to "Sign Up", new_user_path %></li>
            <li><%= link_to "Login", login_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<div class="container-fluid">
  <% flash.each do |name, message| %>
    <div class="alert alert-info flash-message flash-message-<%= name %>">
      <%= message %>
    </div>
  <% end %>

  <%= yield %>
</div>
</body>
</html>